In [2]:
# Pair Numpy
# Creación y Indexación:

In [3]:
import numpy as np

In [4]:
# Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [11]:
np.random.randint(10,100,(50))

array([27, 34, 56, 37, 86, 49, 40, 45, 24, 50, 62, 74, 34, 41, 86, 88, 65,
       51, 90, 86, 90, 22, 53, 50, 64, 90, 42, 14, 26, 90, 10, 17, 15, 22,
       10, 62, 80, 47, 65, 11, 12, 95, 20, 19, 82, 83, 16, 47, 18, 58],
      dtype=int32)

In [12]:
array_cincuenta = np.random.randint(10,100,(50)) 

In [13]:
array_cincuenta[array_cincuenta % 5 == 0]

array([90, 55, 10, 30, 70, 50], dtype=int32)

In [5]:
# Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [15]:
array_treinta = np.random.randint(1,21,(30))

In [17]:
array_treinta

array([ 6,  3,  1, 19, 12, 15,  5,  7,  5,  8, 10, 11, 10,  9,  7,  1, 20,
        3,  9, 17, 18,  8,  4, 10,  3, 11, 20, 20, 12, 12], dtype=int32)

In [ ]:
array_treinta[1::2] ## lenguaje python

array([ 3, 19, 15,  7,  8, 11,  9,  1,  3, 17,  8, 10, 11, 20, 12],
      dtype=int32)

In [ ]:
array_treinta[0::2] ## lenguaje humano

array([ 6,  1, 12,  5,  5, 10, 10,  7, 20,  9, 18,  4,  3, 20, 12],
      dtype=int32)

In [6]:
# Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.


In [38]:
array_1 = np.random.randint(2, 10,(4,6))

In [40]:
array_2 = np.random.rand(4,6)

In [41]:
array_3 = array_1 + array_2


In [42]:
array_3

array([[2.04341243, 5.93900647, 9.3779425 , 8.91055605, 5.90286585,
        5.80325244],
       [3.3167659 , 7.25654058, 9.27726121, 5.65288478, 6.58075717,
        2.94101402],
       [5.56773686, 5.93317899, 4.81410967, 2.90030682, 2.22794362,
        8.2441631 ],
       [7.72847636, 2.72697932, 4.26682551, 7.58125743, 4.61050539,
        2.44847161]])

In [48]:
redondeo = array_3.round(2)
redondeo

array([[2.04, 5.94, 9.38, 8.91, 5.9 , 5.8 ],
       [3.32, 7.26, 9.28, 5.65, 6.58, 2.94],
       [5.57, 5.93, 4.81, 2.9 , 2.23, 8.24],
       [7.73, 2.73, 4.27, 7.58, 4.61, 2.45]])

In [ ]:
# np.round(array_3,2)

array([[2.04, 5.94, 9.38, 8.91, 5.9 , 5.8 ],
       [3.32, 7.26, 9.28, 5.65, 6.58, 2.94],
       [5.57, 5.93, 4.81, 2.9 , 2.23, 8.24],
       [7.73, 2.73, 4.27, 7.58, 4.61, 2.45]])

In [ ]:
redondeo[-1] ## podemos acceder a las filas también con indices negativos

array([7.73, 2.73, 4.27, 7.58, 4.61, 2.45])

In [7]:
# Funciones Aritméticas y Estadísticas:
# Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [8]:








# Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

# Si el valor del array es igual que la media, se reemplaza por "A".

# Si el valor del array es mayor que la media, se reemplaza por "B".

# Si el valor del array es menor que la media, se reemplaza por "C".

# Si el valor es igual que el máximo, se reemplaza por "D".

# Si el valor es igual que el mínimo, se reemplaza por "E".


# Copy
# # a modo de ejemplo. Si tenemos el siguiente array
# [[[0.4, 0.7, 0.2, 0.9, 0.2],
#     [0.1, 0.9, 0.6, 0.1, 0.2],
#     [1. , 0.2, 0.1, 0.8, 0.3]],

# [[0. , 0.3, 0.4, 0.5, 0.1],
#     [0.5, 0.7, 0.9, 0. , 0.8],
#     [0.5, 0.3, 0.5, 0.8, 0.1]]])

# # sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# # nuestro array vacío debería quedar como este: 
# [[["A", "B", "C", "B", "C"],
#     ["C", "B", "B", "C", "C"],
#     ["D" , "C", "C", "B", "C"]],

# [["E" , "C", "A", "B", "C"],
#     ["B", "B","B", "E" , "B"],
#     ["B", "C", "B", "B", "C"]]])
# Si te queda tiempo, puedes hacer los siguientes ejercicios:
# Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

# Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

# Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

# Utiliza el array 3D del ejercicio anterior de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

# Utiliza el array 3D del ejercicio anterior 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

# Previous
# Ejercicios
# Next